#!/bin/bash

export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}

model_name=CANPatchTST

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96_r001_0000_Exchange_96 \
  --model $model_name \
  --data custom \
  --features M \
  --freq d \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 128 \
  --patch_len 16 \
  --can_stride 8 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode full \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.05 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 1 \
  --dropout 0.05 \
  --batch_size 8 \
  --learning_rate 0.0005 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 20 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des EXTSOTA_r001_0000_Exchange_96 \
  --use_amp \
  --max_train_steps 700

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_192_ex192_01 \
  --model $model_name \
  --data custom \
  --features M \
  --freq d \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 128 \
  --patch_len 16 \
  --can_stride 8 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode full \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.05 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 1 \
  --dropout 0.05 \
  --batch_size 8 \
  --learning_rate 0.0005 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 20 \
  --max_train_steps 800 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des R004_ex192_01 \
  --use_amp

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_192_336_r001_0017_Exchange_336 \
  --model $model_name \
  --data custom \
  --features M \
  --freq d \
  --seq_len 192 \
  --label_len 48 \
  --pred_len 336 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 192 \
  --patch_len 16 \
  --can_stride 8 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode full \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.05 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 1 \
  --dropout 0.05 \
  --batch_size 8 \
  --learning_rate 0.0005 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 20 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des EXTSOTA_r001_0017_Exchange_336 \
  --use_amp \
  --max_train_steps 700

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_192_720_r001_0025_Exchange_720 \
  --model $model_name \
  --data custom \
  --features M \
  --freq d \
  --seq_len 192 \
  --label_len 48 \
  --pred_len 720 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 192 \
  --patch_len 16 \
  --can_stride 8 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode full \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.05 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 1 \
  --dropout 0.05 \
  --batch_size 8 \
  --learning_rate 0.0005 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 20 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des EXTSOTA_r001_0025_Exchange_720 \
  --use_amp \
  --max_train_steps 700
