#!/bin/bash

export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}

model_name=CANPatchTST

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id Traffic_384_96_r026_0001_Traffic_96 \
  --model $model_name \
  --data custom \
  --features M \
  --freq h \
  --seq_len 384 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 128 \
  --patch_len 32 \
  --can_stride 16 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode inner \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.05 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 0 \
  --dropout 0.05 \
  --batch_size 2 \
  --learning_rate 0.0002 \
  --lradj cosine \
  --train_epochs 24 \
  --patience 6 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des R011_r026_0001_Traffic_96 \
  --use_amp

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id Traffic_768_192_r026_0002_Traffic_192 \
  --model $model_name \
  --data custom \
  --features M \
  --freq h \
  --seq_len 768 \
  --label_len 48 \
  --pred_len 192 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 128 \
  --patch_len 32 \
  --can_stride 16 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode inner \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.05 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 0 \
  --dropout 0.05 \
  --batch_size 2 \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 12 \
  --patience 6 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des R011_r026_0002_Traffic_192 \
  --use_amp

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id Traffic_1344_336_r026_0004_Traffic_336 \
  --model $model_name \
  --data custom \
  --features M \
  --freq h \
  --seq_len 1344 \
  --label_len 48 \
  --pred_len 336 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 128 \
  --patch_len 32 \
  --can_stride 16 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode inner \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.05 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 0 \
  --dropout 0.05 \
  --batch_size 2 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --train_epochs 24 \
  --patience 6 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des R011_r026_0004_Traffic_336 \
  --use_amp

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id Traffic_512_720_r026_0006_Traffic_720 \
  --model $model_name \
  --data custom \
  --features M \
  --freq h \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 720 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --e_layers 2 \
  --d_model 128 \
  --d_ff 128 \
  --patch_len 16 \
  --can_stride 8 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode inner \
  --can_temporal_cli_mode full \
  --can_ctx_mode diff \
  --can_drop_path 0.02 \
  --can_kernel_size 3 \
  --can_use_gffng 1 \
  --can_temporal_roll 1 \
  --can_context_pyramid 0 \
  --dropout 0.02 \
  --batch_size 2 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --train_epochs 40 \
  --patience 10 \
  --num_workers 0 \
  --itr 1 \
  --seed 2 \
  --des R011_r026_0006_Traffic_720 \
  --use_amp
