export CUDA_VISIBLE_DEVICES=0

python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./dataset/SWAT \
  --model_id SWAT \
  --model CANPatchTST \
  --data SWAT \
  --features M \
  --seq_len 50 \
  --pred_len 0 \
  --enc_in 51 \
  --c_out 51 \
  --e_layers 2 \
  --d_model 64 \
  --d_ff 64 \
  --patch_len 16 \
  --can_stride 8 \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode full \
  --can_temporal_cli_mode full \
  --can_temporal_roll 1 \
  --can_context_pyramid 1 \
  --can_use_gffng 1 \
  --can_drop_path 0.0 \
  --dropout 0.0 \
  --anomaly_ratio 0.5 \
  --batch_size 128 \
  --learning_rate 0.001 \
  --lradj cosine \
  --train_epochs 1 \
  --patience 1 \
  --max_train_steps 300 \
  --use_amp \
  --seed 2 \
  --num_workers 0 \
  --des CAN_SWAT
