export CUDA_VISIBLE_DEVICES=0

python -u run.py \
  --task_name classification \
  --is_training 1 \
  --root_path ./dataset/UWaveGestureLibrary/ \
  --model_id UWaveGestureLibrary \
  --model CANPatchTST \
  --data UEA \
  --e_layers 2 \
  --batch_size 16 \
  --d_model 128 \
  --d_ff 256 \
  --patch_len 8 \
  --can_stride 4 \
  --can_cls_head pool \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode full \
  --can_temporal_cli_mode full \
  --can_temporal_roll 1 \
  --can_context_pyramid 1 \
  --can_use_gffng 1 \
  --dropout 0.1 \
  --can_drop_path 0.02 \
  --learning_rate 0.001 \
  --train_epochs 80 \
  --patience 15 \
  --des CAN_UWaveGestureLibrary \
  --itr 1 \
  --seed 2 \
  --num_workers 0
