export CUDA_VISIBLE_DEVICES=0

python -u run.py \
  --task_name classification \
  --is_training 1 \
  --root_path ./dataset/JapaneseVowels/ \
  --model_id JapaneseVowels \
  --model CANPatchTST \
  --data UEA \
  --e_layers 2 \
  --batch_size 8 \
  --d_model 160 \
  --d_ff 320 \
  --patch_len 4 \
  --can_stride 2 \
  --can_cls_head flatten \
  --can_shifts 1,2,4,8,16 \
  --can_cli_mode inner \
  --can_temporal_cli_mode full \
  --can_temporal_roll 1 \
  --can_context_pyramid 1 \
  --can_use_gffng 1 \
  --dropout 0.05 \
  --can_drop_path 0.02 \
  --learning_rate 0.0005 \
  --use_norm 0 \
  --train_epochs 100 \
  --patience 25 \
  --des CAN_JapaneseVowels \
  --itr 1 \
  --seed 2 \
  --num_workers 0
